import {
  User,
  Listing,
  Order,
  Conversation,
  ChatMessage,
  MarketPriceRecord,
  Complaint,
  PlatformStat,
} from '../types';

export const mockUsers: User[] = [
  {
    _id: 'user_farmer_1',
    role: 'farmer',
    name: 'Sunil Bandara',
    phone: '+94 77 123 4567',
    email: 'sunil.bandara@goviya.lk',
    location: {
      lat: 6.9697,
      lng: 80.7891,
      district: 'Nuwara Eliya',
      address: 'Highland Ridge Farm, Kandapola, Nuwara Eliya',
    },
    verified: true,
    nicNumber: '197412803450',
    farmName: 'Highland Organics Nuwara Eliya',
    farmSizeAcres: 4.5,
    rating: 4.9,
    totalRatings: 128,
    createdAt: '2024-03-15T08:00:00Z',
  },
  {
    _id: 'user_farmer_2',
    role: 'farmer',
    name: 'K. Sivalingam',
    phone: '+94 71 890 1234',
    email: 'sivalingam.k@goviya.lk',
    location: {
      lat: 9.6615,
      lng: 80.0255,
      district: 'Jaffna',
      address: 'Chunnakam Red Soil Farm, Jaffna',
    },
    verified: true,
    nicNumber: '198124901234',
    farmName: 'Jaffna Heritage Onions & Chillies',
    farmSizeAcres: 6.0,
    rating: 4.8,
    totalRatings: 94,
    createdAt: '2024-04-10T10:30:00Z',
  },
  {
    _id: 'user_farmer_3',
    role: 'farmer',
    name: 'Priyani Samarasinghe',
    phone: '+94 76 543 2198',
    email: 'priyani.s@goviya.lk',
    location: {
      lat: 7.8731,
      lng: 80.6511,
      district: 'Matale',
      address: 'Galewela Green Valley, Matale',
    },
    verified: true,
    nicNumber: '198567204918',
    farmName: 'Galewela Agri Collective',
    farmSizeAcres: 3.2,
    rating: 4.7,
    totalRatings: 67,
    createdAt: '2024-05-18T14:15:00Z',
  },
  {
    _id: 'user_farmer_4',
    role: 'farmer',
    name: 'Bandula Wijesinghe',
    phone: '+94 77 456 7890',
    email: 'bandula.w@goviya.lk',
    location: {
      lat: 6.8485,
      lng: 79.9575,
      district: 'Colombo',
      town: 'Pannipitiya',
      address: 'No. 114, High Level Road, Moraketiya, Pannipitiya',
    },
    verified: true,
    nicNumber: '197920401928',
    farmName: 'Pannipitiya Organic Green Agro',
    farmSizeAcres: 2.8,
    rating: 4.9,
    totalRatings: 86,
    createdAt: '2024-04-02T08:00:00Z',
  },
  {
    _id: 'user_farmer_5',
    role: 'farmer',
    name: 'Kusumawathi Jayasinghe',
    phone: '+94 71 678 9012',
    email: 'kusum.agri@goviya.lk',
    location: {
      lat: 6.8520,
      lng: 79.9540,
      district: 'Colombo',
      town: 'Pannipitiya',
      address: 'Arawwala Road, Pannipitiya',
    },
    verified: true,
    nicNumber: '196850201142',
    farmName: 'Pannipitiya Lowland Harvest Farm',
    farmSizeAcres: 3.5,
    rating: 4.8,
    totalRatings: 54,
    createdAt: '2024-05-12T09:30:00Z',
  },
  {
    _id: 'user_buyer_1',
    role: 'buyer',
    name: 'Dinesh Wickramasinghe',
    phone: '+94 77 345 6789',
    email: 'dinesh.w@colombofresh.lk',
    location: {
      lat: 6.9271,
      lng: 79.8612,
      district: 'Colombo',
      address: 'No. 42/3, Havelock Road, Colombo 05',
    },
    verified: true,
    rating: 4.9,
    totalRatings: 32,
    createdAt: '2024-02-01T09:00:00Z',
  },
  {
    _id: 'user_buyer_2',
    role: 'buyer',
    name: 'Kumuduni Senanayake',
    phone: '+94 72 987 6543',
    email: 'kumuduni.s@gmail.com',
    location: {
      lat: 7.2906,
      lng: 80.6337,
      district: 'Kandy',
      address: '28 Peradeniya Road, Kandy',
    },
    verified: true,
    rating: 4.8,
    totalRatings: 18,
    createdAt: '2024-06-20T11:00:00Z',
  },
  {
    _id: 'user_driver_1',
    role: 'driver',
    name: 'Roshan Kaluarachchi',
    phone: '+94 78 234 5678',
    email: 'roshan.logistics@goviya.lk',
    location: {
      lat: 7.084,
      lng: 80.0098,
      district: 'Gampaha',
      address: 'Kadawatha Express Hub, Western Province',
    },
    verified: true,
    vehicleType: 'Light Truck (Dimas)',
    vehiclePlate: 'WP - LG 8824',
    rating: 4.95,
    totalRatings: 215,
    createdAt: '2024-01-12T07:30:00Z',
  },
  {
    _id: 'user_admin_1',
    role: 'admin',
    name: 'Dr. Niluka Jayawardena',
    phone: '+94 11 254 9000',
    email: 'niluka.admin@goviya.lk',
    location: {
      lat: 6.9271,
      lng: 79.8612,
      district: 'Colombo',
      address: 'Goviya Operations HQ, World Trade Center, Colombo 01',
    },
    verified: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const mockListings: Listing[] = [
  {
    _id: 'list_1',
    farmerId: 'user_farmer_1',
    farmerName: 'Sunil Bandara',
    farmerPhone: '+94 77 123 4567',
    farmerRating: 4.9,
    cropName: 'Nuwara Eliya Fresh Carrots',
    category: 'Vegetables',
    quantityKg: 450,
    minOrderKg: 10,
    pricePerKg: 280,
    harvestDate: '2026-10-04',
    photos: ['carrots'],
    description: 'Crisp, sweet mountain carrots freshly harvested at 1,800m altitude in Kandapola. Washed with pure natural spring water.',
    status: 'active',
    location: {
      lat: 6.9697,
      lng: 80.7891,
      district: 'Nuwara Eliya',
      town: 'Kandapola',
    },
    isOrganic: true,
  },
  {
    _id: 'list_2',
    farmerId: 'user_farmer_2',
    farmerName: 'K. Sivalingam',
    farmerPhone: '+94 71 890 1234',
    farmerRating: 4.8,
    cropName: 'Jaffna Premium Red Onions',
    category: 'Vegetables',
    quantityKg: 800,
    minOrderKg: 20,
    pricePerKg: 420,
    harvestDate: '2026-10-03',
    photos: ['onions'],
    description: 'Cured Jaffna red soil shallots with strong aroma and long shelf life. Excellent for commercial kitchen and grocery retail.',
    status: 'active',
    location: {
      lat: 9.6615,
      lng: 80.0255,
      district: 'Jaffna',
      town: 'Chunnakam',
    },
    isOrganic: false,
  },
  {
    _id: 'list_3',
    farmerId: 'user_farmer_3',
    farmerName: 'Priyani Samarasinghe',
    farmerPhone: '+94 76 543 2198',
    farmerRating: 4.7,
    cropName: 'Galewela Green Chillies (Amu Miris)',
    category: 'Spices & Herbs',
    quantityKg: 220,
    minOrderKg: 5,
    pricePerKg: 640,
    harvestDate: '2026-10-05',
    photos: ['chillies'],
    description: 'High pungency grade A green chillies. Picked early morning to guarantee firmness and vibrant green color.',
    status: 'active',
    location: {
      lat: 7.8731,
      lng: 80.6511,
      district: 'Matale',
      town: 'Galewela',
    },
    isOrganic: true,
  },
  {
    _id: 'list_4',
    farmerId: 'user_farmer_1',
    farmerName: 'Sunil Bandara',
    farmerPhone: '+94 77 123 4567',
    farmerRating: 4.9,
    cropName: 'Upcountry Leeks (Prasanna Variety)',
    category: 'Vegetables',
    quantityKg: 300,
    minOrderKg: 10,
    pricePerKg: 240,
    harvestDate: '2026-10-04',
    photos: ['leeks'],
    description: 'Tender white stalks with dark green tops. Packed in breathable 25kg field crates for zero spoilage during transport.',
    status: 'active',
    location: {
      lat: 6.9697,
      lng: 80.7891,
      district: 'Nuwara Eliya',
      town: 'Kandapola',
    },
    isOrganic: true,
  },
  {
    _id: 'list_5',
    farmerId: 'user_farmer_3',
    farmerName: 'Priyani Samarasinghe',
    farmerPhone: '+94 76 543 2198',
    farmerRating: 4.7,
    cropName: 'Dambulla Salad Tomatoes (Thakkali)',
    category: 'Vegetables',
    quantityKg: 500,
    minOrderKg: 15,
    pricePerKg: 310,
    harvestDate: '2026-10-05',
    photos: ['tomatoes'],
    description: 'Firm, sun-ripened greenhouse tomatoes. Semi-ripe stage suitable for 4-day transit with high solid content.',
    status: 'active',
    location: {
      lat: 7.8731,
      lng: 80.6511,
      district: 'Matale',
      town: 'Dambulla',
    },
    isOrganic: false,
  },
  {
    _id: 'list_6',
    farmerId: 'user_farmer_1',
    farmerName: 'Sunil Bandara',
    farmerPhone: '+94 77 123 4567',
    farmerRating: 4.9,
    cropName: 'Red Lady Sweet Papaya',
    category: 'Fruits',
    quantityKg: 650,
    minOrderKg: 25,
    pricePerKg: 190,
    harvestDate: '2026-10-02',
    photos: ['papaya'],
    description: 'Deep salmon-red flesh with high brix sweetness. Average fruit weight 1.5 - 2.0 kg each, packed carefully in foam socks.',
    status: 'active',
    location: {
      lat: 7.4863,
      lng: 80.3623,
      district: 'Kurunegala',
      town: 'Narammala',
    },
    isOrganic: true,
  },
  {
    _id: 'list_7',
    farmerId: 'user_farmer_4',
    farmerName: 'Bandula Wijesinghe',
    farmerPhone: '+94 77 456 7890',
    farmerRating: 4.9,
    cropName: 'Pannipitiya Fresh Brinjal (Wambatu)',
    category: 'Vegetables',
    quantityKg: 280,
    minOrderKg: 5,
    pricePerKg: 220,
    harvestDate: '2026-10-06',
    photos: ['brinjal'],
    description: 'Glossy purple, tender fresh brinjals freshly plucked this morning in Pannipitiya. Zero chemical sprays, pure organic compost fed.',
    status: 'active',
    location: {
      lat: 6.8485,
      lng: 79.9575,
      district: 'Colombo',
      town: 'Pannipitiya',
    },
    isOrganic: true,
  },
  {
    _id: 'list_8',
    farmerId: 'user_farmer_4',
    farmerName: 'Bandula Wijesinghe',
    farmerPhone: '+94 77 456 7890',
    farmerRating: 4.9,
    cropName: 'Pannipitiya Organic Mukunuwenna & Gotukola',
    category: 'Vegetables',
    quantityKg: 180,
    minOrderKg: 5,
    pricePerKg: 140,
    harvestDate: '2026-10-06',
    photos: ['mukunuwenna'],
    description: 'Lush, clean fresh Sri Lankan indigenous leafy greens cultivated in pure well water in Pannipitiya. Packed crisp in breathable bunches.',
    status: 'active',
    location: {
      lat: 6.8485,
      lng: 79.9575,
      district: 'Colombo',
      town: 'Pannipitiya',
    },
    isOrganic: true,
  },
  {
    _id: 'list_9',
    farmerId: 'user_farmer_5',
    farmerName: 'Kusumawathi Jayasinghe',
    farmerPhone: '+94 71 678 9012',
    farmerRating: 4.8,
    cropName: 'Pannipitiya Tender Okra (Bandakka)',
    category: 'Vegetables',
    quantityKg: 350,
    minOrderKg: 8,
    pricePerKg: 180,
    harvestDate: '2026-10-06',
    photos: ['okra'],
    description: 'Young and crisp tender green okra without tough fiber. Plucked at peak tenderness for daily markets and restaurants.',
    status: 'active',
    location: {
      lat: 6.8520,
      lng: 79.9540,
      district: 'Colombo',
      town: 'Pannipitiya',
    },
    isOrganic: true,
  },
  {
    _id: 'list_10',
    farmerId: 'user_farmer_5',
    farmerName: 'Kusumawathi Jayasinghe',
    farmerPhone: '+94 71 678 9012',
    farmerRating: 4.8,
    cropName: 'Pannipitiya Snake Gourd (Pathola)',
    category: 'Vegetables',
    quantityKg: 240,
    minOrderKg: 10,
    pricePerKg: 195,
    harvestDate: '2026-10-05',
    photos: ['gourd'],
    description: 'Straight, uniform organic snake gourd grown on elevated trellises in Pannipitiya. Plump, hydrating, and freshly harvested.',
    status: 'active',
    location: {
      lat: 6.8520,
      lng: 79.9540,
      district: 'Colombo',
      town: 'Pannipitiya',
    },
    isOrganic: true,
  },
  {
    _id: 'list_11',
    farmerId: 'user_farmer_1',
    farmerName: 'Sunil Bandara',
    farmerPhone: '+94 77 123 4567',
    farmerRating: 4.9,
    cropName: 'Kandapola Baby Carrots (Grade A)',
    category: 'Vegetables',
    quantityKg: 280,
    minOrderKg: 5,
    pricePerKg: 340,
    harvestDate: '2026-10-06',
    photos: ['carrots'],
    description: 'Sweet, tender baby carrots with green tops attached. Ideal for supermarkets, fine dining, and organic retail.',
    status: 'active',
    location: {
      lat: 6.9697,
      lng: 80.7891,
      district: 'Nuwara Eliya',
      town: 'Kandapola',
    },
    isOrganic: true,
  },
  {
    _id: 'list_12',
    farmerId: 'user_farmer_3',
    farmerName: 'Priyani Samarasinghe',
    farmerPhone: '+94 76 543 2198',
    farmerRating: 4.7,
    cropName: 'Dambulla Wholesale Orange Carrots',
    category: 'Vegetables',
    quantityKg: 1200,
    minOrderKg: 25,
    pricePerKg: 220,
    harvestDate: '2026-10-05',
    photos: ['carrots'],
    description: 'Commercial wholesale washed carrots in ventilated 50kg crates. Bulk commercial grade from Dambulla agricultural hub.',
    status: 'active',
    location: {
      lat: 7.8731,
      lng: 80.6511,
      district: 'Matale',
      town: 'Dambulla',
    },
    isOrganic: false,
  },
  {
    _id: 'list_13',
    farmerId: 'user_farmer_4',
    farmerName: 'Bandula Wijesinghe',
    farmerPhone: '+94 77 456 7890',
    farmerRating: 4.9,
    cropName: 'Pannipitiya Greenhouse Sweet Carrots',
    category: 'Vegetables',
    quantityKg: 160,
    minOrderKg: 5,
    pricePerKg: 360,
    harvestDate: '2026-10-07',
    photos: ['carrots'],
    description: 'Zero-soil hydroponically grown sweet carrots in Pannipitiya greenhouse. Extra crispy, 100% chemical spray free.',
    status: 'active',
    location: {
      lat: 6.8485,
      lng: 79.9575,
      district: 'Colombo',
      town: 'Pannipitiya',
    },
    isOrganic: true,
  },
  {
    _id: 'list_14',
    farmerId: 'user_farmer_5',
    farmerName: 'Kusumawathi Jayasinghe',
    farmerPhone: '+94 71 678 9012',
    farmerRating: 4.8,
    cropName: 'Nuwara Eliya Organic Jumbo Carrots',
    category: 'Vegetables',
    quantityKg: 650,
    minOrderKg: 15,
    pricePerKg: 260,
    harvestDate: '2026-10-06',
    photos: ['carrots'],
    description: 'Thick, crunchy jumbo soup carrots harvested from organic peat soil in Hakgala valley. High natural brix sugar content.',
    status: 'active',
    location: {
      lat: 6.9200,
      lng: 80.8200,
      district: 'Nuwara Eliya',
      town: 'Hakgala',
    },
    isOrganic: true,
  },
  {
    _id: 'list_15',
    farmerId: 'user_farmer_2',
    farmerName: 'K. Sivalingam',
    farmerPhone: '+94 71 890 1234',
    farmerRating: 4.8,
    cropName: 'Jaffna Sun-Dried Hot Red Chillies',
    category: 'Spices & Herbs',
    quantityKg: 350,
    minOrderKg: 5,
    pricePerKg: 780,
    harvestDate: '2026-10-04',
    photos: ['chillies'],
    description: 'Authentic Jaffna peninsula sun-dried whole red chillies with high pungency and deep red color. Cleaned and graded.',
    status: 'active',
    location: {
      lat: 9.6615,
      lng: 80.0255,
      district: 'Jaffna',
      town: 'Chunnakam',
    },
    isOrganic: true,
  },
  {
    _id: 'list_16',
    farmerId: 'user_farmer_2',
    farmerName: 'K. Sivalingam',
    farmerPhone: '+94 71 890 1234',
    farmerRating: 4.8,
    cropName: 'Jaffna Organic Moringa Drumsticks (Murunga)',
    category: 'Vegetables',
    quantityKg: 200,
    minOrderKg: 5,
    pricePerKg: 290,
    harvestDate: '2026-10-06',
    photos: ['gourd'],
    description: 'Tender fresh Jaffna drumsticks harvested from deep red earth soils. Rich in iron and nutrients, unblemished pods.',
    status: 'active',
    location: {
      lat: 9.6615,
      lng: 80.0255,
      district: 'Jaffna',
      town: 'Chunnakam',
    },
    isOrganic: true,
  },
];

export const mockOrders: Order[] = [
  {
    _id: 'ord_101',
    orderNumber: 'GOV-2026-101',
    buyerId: 'user_buyer_1',
    buyerName: 'Dinesh Wickramasinghe',
    buyerPhone: '+94 77 345 6789',
    farmerId: 'user_farmer_1',
    farmerName: 'Sunil Bandara',
    farmerPhone: '+94 77 123 4567',
    farmerAddress: 'Highland Ridge Farm, Kandapola, Nuwara Eliya',
    driverId: 'user_driver_1',
    driverName: 'Roshan Kaluarachchi',
    driverPhone: '+94 78 234 5678',
    driverVehicle: 'Light Truck (Dimas) · WP - LG 8824',
    items: [
      {
        listingId: 'list_1',
        cropName: 'Nuwara Eliya Fresh Carrots',
        category: 'Vegetables',
        photoUrl: 'carrots',
        quantityKg: 40,
        pricePerKg: 280,
      },
      {
        listingId: 'list_4',
        cropName: 'Upcountry Leeks (Prasanna Variety)',
        category: 'Vegetables',
        photoUrl: 'leeks',
        quantityKg: 25,
        pricePerKg: 240,
      },
    ],
    subtotal: 17200,
    deliveryFee: 1500,
    serviceFee: 350,
    total: 19050,
    paymentMethod: 'cash_on_delivery',
    deliveryAddress: 'No. 42/3, Havelock Road, Colombo 05',
    deliveryDistrict: 'Colombo',
    deliveryNotes: 'Call upon arrival at the gate, delivery reception at back door.',
    status: 'out_for_delivery',
    createdAt: '2026-10-05T08:30:00Z',
    updatedAt: '2026-10-06T03:15:00Z',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: 'Oct 05, 08:30 AM', note: 'Order submitted by Dinesh' },
      { status: 'accepted', label: 'Farmer Confirmed', timestamp: 'Oct 05, 09:15 AM', note: 'Harvest scheduled by Sunil' },
      { status: 'preparing', label: 'Produce Harvested & Packed', timestamp: 'Oct 05, 04:00 PM', note: '65kg verified in wooden crates' },
      { status: 'ready_for_pickup', label: 'Assigned to Driver Roshan', timestamp: 'Oct 06, 01:00 AM', note: 'Route scheduled via A7 highway' },
      { status: 'out_for_delivery', label: 'Picked up & On Route', timestamp: 'Oct 06, 03:15 AM', note: 'Driver on route to Colombo 05' },
    ],
  },
  {
    _id: 'ord_102',
    orderNumber: 'GOV-2026-102',
    buyerId: 'user_buyer_1',
    buyerName: 'Dinesh Wickramasinghe',
    buyerPhone: '+94 77 345 6789',
    farmerId: 'user_farmer_2',
    farmerName: 'K. Sivalingam',
    farmerPhone: '+94 71 890 1234',
    farmerAddress: 'Chunnakam Red Soil Farm, Jaffna',
    driverId: undefined,
    items: [
      {
        listingId: 'list_2',
        cropName: 'Jaffna Premium Red Onions',
        category: 'Vegetables',
        photoUrl: 'onions',
        quantityKg: 50,
        pricePerKg: 420,
      },
    ],
    subtotal: 21000,
    deliveryFee: 2200,
    serviceFee: 400,
    total: 23600,
    paymentMethod: 'card',
    deliveryAddress: 'No. 42/3, Havelock Road, Colombo 05',
    deliveryDistrict: 'Colombo',
    status: 'pending',
    createdAt: '2026-10-06T04:10:00Z',
    updatedAt: '2026-10-06T04:10:00Z',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: 'Oct 06, 04:10 AM', note: 'Awaiting farmer acceptance' },
    ],
  },
  {
    _id: 'ord_103',
    orderNumber: 'GOV-2026-103',
    buyerId: 'user_buyer_2',
    buyerName: 'Kumuduni Senanayake',
    buyerPhone: '+94 72 987 6543',
    farmerId: 'user_farmer_3',
    farmerName: 'Priyani Samarasinghe',
    farmerPhone: '+94 76 543 2198',
    farmerAddress: 'Galewela Green Valley, Matale',
    driverId: 'user_driver_1',
    driverName: 'Roshan Kaluarachchi',
    items: [
      {
        listingId: 'list_3',
        cropName: 'Galewela Green Chillies (Amu Miris)',
        category: 'Spices & Herbs',
        photoUrl: 'chillies',
        quantityKg: 15,
        pricePerKg: 640,
      },
    ],
    subtotal: 9600,
    deliveryFee: 1100,
    serviceFee: 200,
    total: 10900,
    paymentMethod: 'mobile_wallet',
    deliveryAddress: '28 Peradeniya Road, Kandy',
    deliveryDistrict: 'Kandy',
    deliveryType: 'delivery',
    deliveredAt: 'Oct 04, 03:30 PM',
    deliveredBy: 'Roshan Kaluarachchi',
    deliveryProofNote: 'Received and verified at recipient storefront',
    status: 'delivered',
    createdAt: '2026-10-03T10:00:00Z',
    updatedAt: '2026-10-04T15:30:00Z',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: 'Oct 03, 10:00 AM' },
      { status: 'accepted', label: 'Farmer Confirmed', timestamp: 'Oct 03, 11:30 AM' },
      { status: 'preparing', label: 'Produce Ready', timestamp: 'Oct 04, 07:00 AM' },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: 'Oct 04, 11:00 AM' },
      { status: 'delivered', label: 'Delivered Successfully', timestamp: 'Oct 04, 03:30 PM', note: 'Received and signed by Kumuduni' },
    ],
  },
  {
    _id: 'ord_104',
    orderNumber: 'GOV-2026-104',
    buyerId: 'user_buyer_1',
    buyerName: 'Dinesh Wickramasinghe',
    buyerPhone: '+94 77 345 6789',
    farmerId: 'user_farmer_1',
    farmerName: 'Sunil Bandara',
    farmerPhone: '+94 77 123 4567',
    farmerAddress: 'Highland Ridge Farm, Kandapola, Nuwara Eliya',
    items: [
      {
        listingId: 'list_1',
        cropName: 'Nuwara Eliya Fresh Carrots',
        category: 'Vegetables',
        photoUrl: 'carrots',
        quantityKg: 30,
        pricePerKg: 280,
      },
    ],
    subtotal: 8400,
    deliveryFee: 0,
    serviceFee: 0,
    total: 8400,
    paymentMethod: 'cash_on_delivery',
    deliveryType: 'pickup',
    pickupLocation: {
      lat: 6.9697,
      lng: 80.7891,
      district: 'Nuwara Eliya',
      town: 'Kandapola',
      address: 'Highland Ridge Farm, Kandapola, Nuwara Eliya',
      directions: 'Located 2km past Kandapola post office on Pedro road.',
    },
    pickupPin: '4821',
    preparationNote: 'Harvested freshly from field, washed, sorted Grade A and packed in crates',
    deliveryAddress: 'Direct Farm Gate Pickup (Kandapola)',
    deliveryDistrict: 'Nuwara Eliya',
    status: 'ready_for_pickup',
    createdAt: '2026-10-07T06:00:00Z',
    updatedAt: '2026-10-07T07:15:00Z',
    timeline: [
      { status: 'pending', label: 'Order Placed (Farm Self-Pickup)', timestamp: '06:00 AM', note: 'Direct farm gate pickup requested' },
      { status: 'accepted', label: 'Farmer Accepted', timestamp: '06:20 AM', note: 'Sunil scheduled morning harvest' },
      { status: 'preparing', label: 'Harvesting & Packing in Crates', timestamp: '06:45 AM', note: 'Freshly washed and packed into 30kg crate' },
      { status: 'ready_for_pickup', label: 'Ready for Buyer Farm Gate Pickup', timestamp: '07:15 AM', note: 'Harvest is packed and ready at farm gate! Bring PIN #4821.' },
    ],
  },
];

export const mockConversations: Conversation[] = [
  {
    _id: 'conv_1',
    participants: [
      { userId: 'user_buyer_1', name: 'Dinesh Wickramasinghe', role: 'buyer' },
      { userId: 'user_farmer_1', name: 'Sunil Bandara', role: 'farmer' },
    ],
    lastMessage: 'I have packed 40kg of grade A carrots with the morning harvest.',
    lastMessageAt: '2026-10-05T09:20:00Z',
    unreadCount: 0,
    relatedCropName: 'Nuwara Eliya Fresh Carrots',
  },
  {
    _id: 'conv_2',
    participants: [
      { userId: 'user_buyer_1', name: 'Dinesh Wickramasinghe', role: 'buyer' },
      { userId: 'user_farmer_2', name: 'K. Sivalingam', role: 'farmer' },
    ],
    lastMessage: 'Can you guarantee delivery to Colombo by Thursday evening?',
    lastMessageAt: '2026-10-06T04:12:00Z',
    unreadCount: 1,
    relatedCropName: 'Jaffna Premium Red Onions',
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    _id: 'msg_1',
    conversationId: 'conv_1',
    senderId: 'user_buyer_1',
    senderRole: 'buyer',
    type: 'product',
    content: 'Inquiring about this batch for wholesale delivery to Colombo',
    listingId: 'list_1',
    listingData: {
      cropName: 'Nuwara Eliya Fresh Carrots',
      pricePerKg: 280,
      photo: 'carrots',
    },
    sentAt: '2026-10-05T08:15:00Z',
  },
  {
    _id: 'msg_2',
    conversationId: 'conv_1',
    senderId: 'user_farmer_1',
    senderRole: 'farmer',
    type: 'text',
    content: 'Ayubowan Dinesh mahaththaya! Yes, this batch is freshly pulled this morning from Kandapola. Soil moisture is optimal.',
    sentAt: '2026-10-05T08:22:00Z',
  },
  {
    _id: 'msg_3',
    conversationId: 'conv_1',
    senderId: 'user_buyer_1',
    senderRole: 'buyer',
    type: 'order_request',
    content: 'Placed order request for 40kg Carrots + 25kg Leeks',
    orderRequestData: {
      cropName: 'Nuwara Eliya Carrots & Leeks',
      quantityKg: 65,
      offerPricePerKg: 280,
    },
    sentAt: '2026-10-05T08:31:00Z',
  },
  {
    _id: 'msg_4',
    conversationId: 'conv_1',
    senderId: 'user_farmer_1',
    senderRole: 'farmer',
    type: 'text',
    content: 'I have packed 40kg of grade A carrots with the morning harvest. Roshan driver will collect it tonight!',
    sentAt: '2026-10-05T09:20:00Z',
  },
];

export const mockMarketPrices: MarketPriceRecord[] = [
  {
    id: 'mp_1',
    crop: 'Carrots',
    sinhalaName: 'කැරට්',
    marketName: 'Dambulla Dedicated Economic Centre',
    wholesaleMinLkr: 240,
    wholesaleMaxLkr: 290,
    retailAvgLkr: 380,
    changePercentage: 8.5,
    trend: 'up',
    updatedAt: '2026-10-06 05:00 AM',
    history6Months: [
      { month: 'May', price: 210 },
      { month: 'Jun', price: 225 },
      { month: 'Jul', price: 260 },
      { month: 'Aug', price: 250 },
      { month: 'Sep', price: 265 },
      { month: 'Oct', price: 285 },
    ],
  },
  {
    id: 'mp_2',
    crop: 'Red Onions (Shallots)',
    sinhalaName: 'රතු ළුණු',
    marketName: 'Dambulla & Pettah Wholesale',
    wholesaleMinLkr: 390,
    wholesaleMaxLkr: 440,
    retailAvgLkr: 560,
    changePercentage: -4.2,
    trend: 'down',
    updatedAt: '2026-10-06 05:00 AM',
    history6Months: [
      { month: 'May', price: 480 },
      { month: 'Jun', price: 460 },
      { month: 'Jul', price: 450 },
      { month: 'Aug', price: 430 },
      { month: 'Sep', price: 425 },
      { month: 'Oct', price: 415 },
    ],
  },
  {
    id: 'mp_3',
    crop: 'Green Chillies (Amu Miris)',
    sinhalaName: 'අමු මිරිස්',
    marketName: 'Dambulla Dedicated Economic Centre',
    wholesaleMinLkr: 580,
    wholesaleMaxLkr: 660,
    retailAvgLkr: 820,
    changePercentage: 14.1,
    trend: 'up',
    updatedAt: '2026-10-06 05:00 AM',
    history6Months: [
      { month: 'May', price: 420 },
      { month: 'Jun', price: 450 },
      { month: 'Jul', price: 510 },
      { month: 'Aug', price: 540 },
      { month: 'Sep', price: 590 },
      { month: 'Oct', price: 640 },
    ],
  },
  {
    id: 'mp_4',
    crop: 'Leeks',
    sinhalaName: 'ලීක්ස්',
    marketName: 'Meegoda Economic Centre',
    wholesaleMinLkr: 210,
    wholesaleMaxLkr: 250,
    retailAvgLkr: 330,
    changePercentage: 0.5,
    trend: 'stable',
    updatedAt: '2026-10-06 05:00 AM',
    history6Months: [
      { month: 'May', price: 230 },
      { month: 'Jun', price: 240 },
      { month: 'Jul', price: 220 },
      { month: 'Aug', price: 235 },
      { month: 'Sep', price: 240 },
      { month: 'Oct', price: 238 },
    ],
  },
  {
    id: 'mp_5',
    crop: 'Tomatoes',
    sinhalaName: 'තක්කාලි',
    marketName: 'Dambulla Dedicated Economic Centre',
    wholesaleMinLkr: 280,
    wholesaleMaxLkr: 320,
    retailAvgLkr: 420,
    changePercentage: -6.8,
    trend: 'down',
    updatedAt: '2026-10-06 05:00 AM',
    history6Months: [
      { month: 'May', price: 340 },
      { month: 'Jun', price: 360 },
      { month: 'Jul', price: 330 },
      { month: 'Aug', price: 350 },
      { month: 'Sep', price: 320 },
      { month: 'Oct', price: 300 },
    ],
  },
  {
    id: 'mp_6',
    crop: 'Beans (Green Pole)',
    sinhalaName: 'බෝංචි',
    marketName: 'Pettah Manning Market',
    wholesaleMinLkr: 310,
    wholesaleMaxLkr: 370,
    retailAvgLkr: 490,
    changePercentage: 3.2,
    trend: 'up',
    updatedAt: '2026-10-06 05:00 AM',
    history6Months: [
      { month: 'May', price: 300 },
      { month: 'Jun', price: 320 },
      { month: 'Jul', price: 340 },
      { month: 'Aug', price: 330 },
      { month: 'Sep', price: 350 },
      { month: 'Oct', price: 360 },
    ],
  },
];

export const mockComplaints: Complaint[] = [
  {
    _id: 'cmp_1',
    complainantId: 'user_buyer_1',
    complainantName: 'Dinesh Wickramasinghe',
    targetId: 'user_farmer_3',
    targetName: 'Galewela Agri Collective',
    targetType: 'listing',
    reason: 'Listing weight discrepancy',
    details: 'Received 12kg instead of ordered 15kg green chillies on batch GW-88. Requesting partial refund or replacement.',
    severity: 'medium',
    status: 'pending',
    createdAt: '2026-10-04T12:00:00Z',
  },
  {
    _id: 'cmp_2',
    complainantId: 'user_farmer_1',
    complainantName: 'Sunil Bandara',
    targetId: 'user_buyer_2',
    targetName: 'Kumuduni Senanayake',
    targetType: 'buyer',
    reason: 'Repeated cancellation after harvest',
    details: 'Buyer cancelled 60kg beans order after harvesting was completed at 6:00 AM. Incurred packaging loss.',
    severity: 'high',
    status: 'pending',
    createdAt: '2026-10-03T09:45:00Z',
  },
  {
    _id: 'cmp_3',
    complainantId: 'user_driver_1',
    complainantName: 'Roshan Kaluarachchi',
    targetId: 'user_farmer_2',
    targetName: 'K. Sivalingam',
    targetType: 'farmer',
    reason: 'Pickup delay exceeding 90 minutes',
    details: 'Scheduled pickup at Chunnakam farm delayed due to unwashed produce crates.',
    severity: 'low',
    status: 'resolved',
    resolutionNote: 'Farmer was issued guidance on pre-packing deadlines. Closed with mutual agreement.',
    createdAt: '2026-09-28T16:20:00Z',
  },
];

export const mockPlatformStats: PlatformStat = {
  totalFarmers: 1420,
  totalBuyers: 3890,
  totalDrivers: 245,
  totalTransactionsLkr: 86450000,
  activeListingsCount: 840,
  completedDeliveriesCount: 4210,
  topCrops: [
    { crop: 'Nuwara Eliya Carrots', volumeKg: 42000, revenueLkr: 11760000 },
    { crop: 'Jaffna Red Onions', volumeKg: 38000, revenueLkr: 15960000 },
    { crop: 'Green Chillies', volumeKg: 19500, revenueLkr: 12480000 },
    { crop: 'Upcountry Leeks', volumeKg: 28000, revenueLkr: 6720000 },
    { crop: 'Dambulla Tomatoes', volumeKg: 35000, revenueLkr: 10850000 },
  ],
  monthlyVolume: [
    { month: 'May', volumeTons: 110, valueMillionsLkr: 14.2 },
    { month: 'Jun', volumeTons: 135, valueMillionsLkr: 17.5 },
    { month: 'Jul', volumeTons: 152, valueMillionsLkr: 19.8 },
    { month: 'Aug', volumeTons: 170, valueMillionsLkr: 22.1 },
    { month: 'Sep', volumeTons: 198, valueMillionsLkr: 25.6 },
    { month: 'Oct', volumeTons: 225, valueMillionsLkr: 28.9 },
  ],
};
